// generated by tools/analyze_audio.py, do not edit by hand
(function (root) { const META = {
 "sfx": {
  "click-check": {
   "dur": 0.237,
   "hit": 0.093,
   "norm": 2.02
  },
  "click-select": {
   "dur": 1.553,
   "hit": 0.116,
   "norm": 0.478
  },
  "click-soft": {
   "dur": 1.104,
   "hit": 0.058,
   "norm": 0.91
  },
  "click-tone": {
   "dur": 0.2,
   "hit": 0.0,
   "norm": 1.249
  },
  "confirm": {
   "dur": 1.304,
   "hit": 0.186,
   "norm": 0.878
  },
  "energy-flow": {
   "dur": 7.413,
   "hit": 1.904,
   "norm": 0.663
  },
  "hint": {
   "dur": 1.716,
   "hit": 0.453,
   "norm": 4.823
  },
  "impact-intro": {
   "dur": 5.994,
   "hit": 1.393,
   "norm": 0.621
  },
  "impact-logo": {
   "dur": 8.973,
   "hit": 4.435,
   "norm": 0.706
  },
  "pop-hard": {
   "dur": 1.175,
   "hit": 0.035,
   "norm": 0.66
  },
  "pop-light": {
   "dur": 0.18,
   "hit": 0.023,
   "norm": 0.573
  },
  "pop-long": {
   "dur": 0.479,
   "hit": 0.035,
   "norm": 0.573
  },
  "power-up": {
   "dur": 2.813,
   "hit": 0.708,
   "norm": 1.019
  },
  "sparkle": {
   "dur": 3.5,
   "hit": 0.453,
   "norm": 1.748
  },
  "sweep-air": {
   "dur": 0.861,
   "hit": 0.313,
   "norm": 0.972
  },
  "sweep-small": {
   "dur": 0.781,
   "hit": 0.29,
   "norm": 0.775
  },
  "swish-short": {
   "dur": 1.39,
   "hit": 0.163,
   "norm": 0.791
  },
  "swish-wind": {
   "dur": 1.452,
   "hit": 0.43,
   "norm": 0.981
  },
  "swoosh-fast": {
   "dur": 0.574,
   "hit": 0.104,
   "norm": 1.762
  },
  "tech-select": {
   "dur": 0.5,
   "hit": 0.012,
   "norm": 0.658
  },
  "typing-soft": {
   "dur": 26.213,
   "hit": 20.167,
   "norm": 1.605
  },
  "whoosh-cinematic": {
   "dur": 1.334,
   "hit": 1.08,
   "norm": 1.131
  },
  "whoosh-fast": {
   "dur": 1.757,
   "hit": 0.72,
   "norm": 1.414
  },
  "whoosh-ghost": {
   "dur": 3.761,
   "hit": 2.612,
   "norm": 0.916
  },
  "woosh-tunnel": {
   "dur": 6.747,
   "hit": 0.615,
   "norm": 0.603
  }
 },
 "music": {
  "tech-house-vibes": {
   "dur": 102.374,
   "bpm": 123.05,
   "beat": 0.4876,
   "phase": 0.058
  }
 }
};
if (typeof module !== 'undefined') module.exports = META; else root.SOUND_META = META; })(this);
