"""Measure every clip in assets/audio and write lib/sound-meta.js.

For each sound effect:  dur (s), hit (s from file start to its loudest point, so cues can land the
transient exactly on the visual beat) and norm (gain that brings its loud part to a common level).
For each music track:   dur, bpm, and the time of the first beat (phase), used to put a beat on the logo hit.

Run again after adding or replacing audio:  python tools/analyze_audio.py
Needs numpy and ffmpeg on PATH.
"""
import json, os, subprocess, sys
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO = os.path.join(ROOT, 'assets', 'audio')
SR, HOP = 22050, 256


def load(path):
    raw = subprocess.run(['ffmpeg', '-v', 'error', '-i', path, '-ac', '1', '-ar', str(SR), '-f', 's16le', '-'],
                         capture_output=True, check=True).stdout
    return np.frombuffer(raw, np.int16).astype(np.float32) / 32768


def frames(x):
    n = len(x) // HOP
    return x[:n * HOP].reshape(n, HOP)


def sfx_meta(x):
    env = np.sqrt((frames(x) ** 2).mean(1))
    peak_i = int(np.argmax(env))
    # the moment the clip "lands": its loudest point (for risers and swells that is the payoff, for clicks the attack)
    hit_i = peak_i
    loud = env[env >= env.max() * .25]
    level = 20 * np.log10(np.sqrt((loud ** 2).mean()) + 1e-9)
    norm = 10 ** ((-16 - level) / 20)                       # loud part → -16 dBFS RMS
    norm = min(norm, 10 ** (-1 / 20) / (np.abs(x).max() + 1e-9))   # never push peaks past -1 dBFS
    return {'dur': round(len(x) / SR, 3), 'hit': round(hit_i * HOP / SR, 3), 'norm': round(float(norm), 3)}


def music_meta(x):
    f = frames(x) * np.hanning(HOP)
    spec = np.abs(np.fft.rfft(f, axis=1))
    flux = np.maximum(np.diff(spec, axis=0), 0).sum(1)
    flux = np.maximum(flux - np.convolve(flux, np.ones(32) / 32, 'same'), 0)
    fps = SR / HOP
    seg = flux[:int(60 * fps)]
    ac = np.correlate(seg, seg, 'full')[len(seg) - 1:]
    lags = np.arange(len(ac))
    bpm = 60 * fps / np.maximum(lags, 1)
    ok = (bpm > 90) & (bpm < 160)
    lag = lags[ok][np.argmax(ac[ok])]
    # refine the period, then find the phase with the strongest onsets on the grid
    period = lag / fps
    best = (0, 0)
    for ph in np.arange(0, period, 1 / fps):
        idx = ((ph + np.arange(0, len(x) / SR - 1, period)) * fps).astype(int)
        idx = idx[idx < len(flux)]
        s = flux[idx].sum()
        if s > best[0]:
            best = (s, ph)
    return {'dur': round(len(x) / SR, 3), 'bpm': round(60 / period, 2), 'beat': round(period, 4), 'phase': round(float(best[1]), 4)}


def main():
    meta = {'sfx': {}, 'music': {}}
    for name in sorted(os.listdir(os.path.join(AUDIO, 'sfx'))):
        meta['sfx'][name[:-4]] = sfx_meta(load(os.path.join(AUDIO, 'sfx', name)))
    for name in sorted(os.listdir(os.path.join(AUDIO, 'music'))):
        meta['music'][name[:-4]] = music_meta(load(os.path.join(AUDIO, 'music', name)))
    out = os.path.join(ROOT, 'lib', 'sound-meta.js')
    body = json.dumps(meta, indent=1)
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write('// generated by tools/analyze_audio.py, do not edit by hand\n'
                 "(function (root) { const META = " + body + ";\n"
                 "if (typeof module !== 'undefined') module.exports = META; else root.SOUND_META = META; })(this);\n")
    for k, v in meta['music'].items():
        print(k, v)
    for k, v in meta['sfx'].items():
        print(f'{k:18s} {v}')


if __name__ == '__main__':
    sys.exit(main())
